### ISSUE TITLE
we fwefewf

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1013]
Gksmao976rgEJvhR54JkTCQefXDTmFVErtmCPjqywJXj1tS

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0xda496ac2f2e69a9db4e89f6b03094c1a938bda8cf0f565b45edfb702bf1df2bf
