### ISSUE TITLE
f wfwe

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1047]
Gksmao976rgEJvhR54JkTCQefXDTmFVErtmCPjqywJXj1tS

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0xf7988e96a2e9060c85a6bd514abb0ae616ad2004e11f42f0415a8cdcb5693a0d
