### ISSUE TITLE
wf we

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1059]
Gksmao976rgEJvhR54JkTCQefXDTmFVErtmCPjqywJXj1tS

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x15aec2a6142c2d5138f23ae4e08b4a14cae87155b30c0bb94bbf2730bd826a2b
