### ISSUE TITLE
wf wfwfwe

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1080]
HjksmaQKnK9sdcZwYHiJNqvKHAdpiQKvKJM16NnCTCwNGd8

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x2e79ab872e7f857b9783b217f176f5657208f873fb7195c053d557bb353ccad5
