### ISSUE TITLE
fwe fw

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1086]
GksmaWekAP7SoXCFEKutQbwVJvfLG4VC4QKwcu29ycDoRw5

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x092c5d04bfe1ccde2a722cbcafb2694e6d75475a3c683b32e5bd0ec7bb00a33e
