### ISSUE TITLE
w fwefffff faucet

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1092]
Gksmao976rgEJvhR54JkTCQefXDTmFVErtmCPjqywJXj1tS

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x85755efa06fa0ff1c364f73b8445e69e2b96840c05ff003b67884dd89f8dbadb
