### ISSUE TITLE
ew fwefew

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1100]
Gksmao976rgEJvhR54JkTCQefXDTmFVErtmCPjqywJXj1tS

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0xe95801ff497be3f9cf3b5ac46aeced61eb63f5a8aa9f63949cadab959125513c
