### ISSUE TITLE
wefef

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1140]
D5ksmatpeysdQhYzks8BEdroDa3SsnGRZLxhQwdEUL7yMSt

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x7d3c95ab8583f525054c5d1f57a4ac4c683bfd486ae7db6df822f41c193ee305
