### ISSUE TITLE
fwef ew

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#1164]
HjksmaQKnK9sdcZwYHiJNqvKHAdpiQKvKJM16NnCTCwNGd8

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x08566e13a80a1723ec3cca0d6b123cde139997acb1d187d9f49dafdc7b25ec70
