### ISSUE TITLE
fwefwe

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#457]
JKSmaWrutkmi6Zd35pXQJxbXc94S1532qU88NtkDimGLv21

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc2/transaction/0x6e3d58483aeb834e5189c3fa4b0148318c9eb8072654b20093cee4a2b2d5fa4e
