### ISSUE TITLE
vwewefwefew

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#596]
FkSMauVZz2ongny6dgE4q7dG5wExFoUKGFTu1Vbk9njodqi

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0xeff0e8be22fe904a16ede243db819ebbf9b968c1204de01ce9050b33faeafbcd
