### ISSUE TITLE
wefwefwefwe 

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#669]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x7eedd6d2b4d4f093c60e778252cb0f8a5626ee57cf748afa4a52d615d3a3c859
