### ISSUE TITLE
 fwef wefwe

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#680]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x02233af2ee700fe4cf1e013766fba9ad7e0b70c6287a8f401b4e488d1c422f05
