### ISSUE TITLE
fwef wefwef

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#685]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x5efb61c5d852c81d98c6408c605a9b9034feb8316927edb78cac113578295dad
