### ISSUE TITLE
fff

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#701]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x51530c6faf2d0ffc16da0fcb8ebf065dc68c991eb6facd862bfc5fb5b379d930
