### ISSUE TITLE
fwe fwe

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#724]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x61b7bd2e2835db52554bd24226523300bc176a8c21c6cdf73b25e9c3a0bc8099
