### ISSUE TITLE
wf ew

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#751]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0xc9960d07f99de8aa1bc61368d1e41bb5736b91fa63ea3c43a80b7654c742d9a5
