### ISSUE TITLE
 fewfw efew

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#763]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0xa881679d156ee9e1bf4a9907a88b4b602112c5cc8c74d0bcfd545c45644d9d8f
