### ISSUE TITLE
 wfwefewf

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#772]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x30527270105b8a889b06add1761513f9be87b0c0ca76f938172fa84cc8f34461
