### ISSUE TITLE
 gerg reg

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#776]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
This address has been used.

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x5eb29f8ad21f3fb1c95ca62062187db15f6c1180a02ceb1105f68a4f99a7e971
