### ISSUE TITLE
wef fee

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#818]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x7660fbe31b073cc75b7526f381b07bcb840d87b58bc8eb55080972e2b1eb9615
