### ISSUE TITLE
fewf we

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#839]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x67c584bfa157561cd1e7aa98ce97f0ffed75b6851df546ab3dce3fc4aa706ef6
