### ISSUE TITLE
wf wefewf

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#861]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/analytics/search/0x784217d6646caf563ac09d8ff8d7b1376c13c7d5a845516de91b2d5fe0a94b56
