### ISSUE TITLE
 wf

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#904]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
You have already opened an issue that needs to be processed first.

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x6f46a1ad9bfb185a6429996ad8675d85dfa5eea106cc0a4d5ce993dfba287ac5
