### ISSUE TITLE
w fwe

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#916]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
You have already opened an issue that needs to be processed first.

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x986044d97782d0137c492eb986172e7a1ccba178ab021c63703a5d813aa8b601
