### ISSUE TITLE
few fewfe

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#937]
FkSMA56tB4omR8ZzxNqNoxyjMHavNExrDSKK8EgLi1QuVno

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0xf04151e9c832ffcf3df773db4fcf819c3de1b33eb7eeb2c9ced44cb10afe1e96
