### ISSUE TITLE
wfwe f

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#958]
Gksmao976rgEJvhR54JkTCQefXDTmFVErtmCPjqywJXj1tS

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0xecf8c60ad809355216176b8bf975d24f9eaa918ff6d7a75c00d8bce0fcf39aa3
