### ISSUE TITLE
wefewf

### ISSUE THREAD

**Issue by chauwoyuk** [ansonla3/testing#988]
Gksmao976rgEJvhR54JkTCQefXDTmFVErtmCPjqywJXj1tS

**Comment by ansonla3** [comment]
Sent 0.1 KSM with transaction hash: https://polkascan.io/pre/kusama-cc3/transaction/0x20c9e234884dd8daffc005907feff22873ed210cd65ec3ffd4c1e2ce590319e5

**Comment by ansonla3** [comment]
This address has already been dripped before.

**Comment by ansonla3** [comment]
This address has already been dripped before.
